# Generated by Django 4.1.3 on 2022-12-17 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClimInputs",
            fields=[
                (
                    "scenario",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("start_year", models.PositiveIntegerField()),
                ("decarb_period", models.PositiveIntegerField()),
                ("final_emiss", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="ClimOutputs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("f_ha", models.FloatField()),
                ("atmos_co2", models.FloatField()),
                ("ocean_co2", models.FloatField()),
                ("ocean_ph", models.FloatField()),
                ("t_C", models.FloatField()),
                ("t_F", models.FloatField()),
                ("t_anomaly", models.FloatField()),
                ("albedo", models.FloatField()),
                ("f_oa", models.FloatField()),
                ("f_la", models.FloatField()),
                ("tot_ha", models.FloatField()),
                (
                    "scenario",
                    models.ForeignKey(
                        db_column="scenario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="benchly.climinputs",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="climoutputs",
            constraint=models.UniqueConstraint(
                fields=("scenario", "year"), name="unique_migration_host_combination"
            ),
        ),
    ]
