# Generated by Django 4.1.3 on 2022-11-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benchly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeseriesVar',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('climvar', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('scenario', models.ForeignKey(db_column='scenario', on_delete=django.db.models.deletion.CASCADE, to='benchly.climinputs')),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('user', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('scenario', models.ForeignKey(db_column='scenario', on_delete=django.db.models.deletion.CASCADE, to='benchly.climinputs')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='benchly.climoutputs')),
            ],
        ),
        migrations.AddConstraint(
            model_name='timeseries',
            constraint=models.UniqueConstraint(fields=('user', 'scenario'), name='unique_migration_host_combination2'),
        ),
    ]
