# Generated by Django 4.1.3 on 2022-11-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benchly', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inputs',
            new_name='ClimInputs',
        ),
        migrations.RenameModel(
            old_name='Outputs',
            new_name='ClimOutputs',
        ),
    ]
