# Generated by Django 4.1.3 on 2022-11-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benchly', '0002_timeseriesvar_timeseries_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climoutputs',
            name='scenario',
            field=models.ForeignKey(db_column='scenario', on_delete=django.db.models.deletion.CASCADE, to='benchly.climinputs'),
        ),
    ]
