# Generated by Django 4.1.3 on 2022-11-19 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('benchly', '0002_rename_inputs_climinputs_rename_outputs_climoutputs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climoutputs',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.climinputs'),
        ),
    ]
