# Generated by Django 4.1.3 on 2022-11-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.PositiveIntegerField()),
                ('start_year', models.PositiveIntegerField()),
                ('final_emiss', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Outputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('atmos_co2', models.FloatField()),
                ('ocean_co2', models.FloatField()),
            ],
        ),
    ]
